# Generated by Django 5.1.1 on 2024-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='The ticker for Apple is AAPL, Vale is VALE3.SA... ', max_length=30, verbose_name='Ticker')),
                ('current_price', models.FloatField(null=True)),
                ('current_open', models.FloatField(null=True)),
                ('pe_ratio', models.FloatField(null=True)),
                ('moment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
